### ISSUE TITLE
Add support for IBMDSwitcherDisplayClock

### ISSUE THREAD

**Issue by gletiecq** [Sofie-Automation/sofie-atem-connection#138] opened 2023-02-13 15:34 UTC
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
The BM API has features that at least some of the Constellation ATEMS can use to display a countdown timer on AUX1.  

I have been using this feature in shows frequently, but have to use macros to provide this functionality with bitfocus companion.  If the atem-connection module supported this directly, it would be a much easier and more flexible interface for this feature.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)**  

The API documents this in section 13.2 (page 656) and the BMDSwitcherAPI.idl provides the interface definitions starting in lines 1223-1250 and 3942-3986.

**Comment by Julusian** [comment] 2023-02-13 15:43
Duplicate of #135

**Closed as not planned by Julusian** 2023-02-13 15:43 UTC
