### ISSUE TITLE
Topology (_top) information correctness

### ISSUE THREAD

**Issue by Dev1an** [Sofie-Automation/sofie-atem-connection#78] opened 2020-04-17 20:16 UTC
From where do you know that byte 8 describes the `DVE`'s?
My Atem 1 M/E Production Studio 4K gives me `04` for this value. And I know that this atem only has one DVE. So I think this is incorrect.

https://github.com/nrkno/tv-automation-atem-connection/blob/3f8cfe7bdd7434b193c4807fc521546b3790c1ad/src/commands/DeviceProfile/topologyCommand.ts#L18

**Comment by Julusian** [comment] 2020-04-17 20:26
Accidental duplicate of #79

**Closed as completed by Julusian** 2020-04-17 20:26 UTC
