### ISSUE TITLE
Feature Request: Camera control

### ISSUE THREAD

**Issue by haydendonald** [Sofie-Automation/sofie-atem-connection#105] opened 2021-03-04 03:41 UTC
* **I'm submitting a feature request**
[ ] bug report
[ X] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
* Hi, great library!
I was wondering if there was a possibility of adding camera control to the supported commands so that we can control the cameras for CCU purposes.
This will be greatly appreciated! 

Thanks heaps

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
* None

**Comment by Julusian** [comment] 2021-03-04 10:01
Duplicate of #85

**Closed as completed by Julusian** 2021-03-04 10:01 UTC
Labels: duplicate, enhancement
